load('Ikeda_daitai');
No1 = daitai_maxpoint_FFT;
load('Nabe_daitai');
No2 = daitai_maxpoint_FFT;
load('Monobe_daitai');
No3 = daitai_maxpoint_FFT;
load('Suzuki_daitai');
No4 = daitai_maxpoint_FFT;
load('Kaito_daitai');
No5 = daitai_maxpoint_FFT;
load('Okamura_daitai');
No6 = daitai_maxpoint_FFT;
load('Takechi_daitai');
No7 = daitai_maxpoint_FFT;
load('Tsuji_daitai');
No8 = daitai_maxpoint_FFT;
load('Usui_daitai');
No9 = daitai_maxpoint_FFT;
load('Rikiya_daitai');
No10 = daitai_maxpoint_FFT;
load('Yamao_daitai');
No11 = daitai_maxpoint_FFT;
sokutei = [1 2 3];
figure;
plot(sokutei,No1,'-o');
xlabel('測定日');
ylabel('emgRMS');
title('大腿直筋');
xticks([1 2 3])
xticklabels({'初回測定','中間測定','最終測定'})
hold on;
plot(sokutei,No2,'-o');
hold on;
plot(sokutei,No3,'-o');
hold on;
plot(sokutei,No4,'-o');
hold on;
plot(sokutei,No5,'-o');
hold on;
plot(sokutei,No6,'-o');
hold on;
plot(sokutei,No7,'-o');
hold on;
plot(sokutei,No8,'-o');
hold on;
plot(sokutei,No9,'-o');
hold on;
plot(sokutei,No10,'-o');
hold on;
plot(sokutei,No11,'-o');
legend({'Ikeda','Watanabe','Monobe','Suzuki','Takano','Okamura','Takechi','Tsuji','Usui','Fujii','Yamao'},'Location','northwest','NumColumns',2);
data = vertcat(No1,No2,No3,No4,No5,No6,No7,No8,No8,No9,No10,No11);
[h p] = ttest(data(:,1),data(:,3));

load('Ikeda_gaisoku');
No1 = gaisoku_maxpoint_FFT;
load('Nabe_gaisoku');
No2 = gaisoku_maxpoint_FFT;
load('Monobe_gaisoku');
No3 = gaisoku_maxpoint_FFT;
load('Suzuki_gaisoku');
No4 = gaisoku_maxpoint_FFT;
load('Kaito_gaisoku');
No5 = gaisoku_maxpoint_FFT;
load('Okamura_gaisoku');
No6 = gaisoku_maxpoint_FFT;
load('Takechi_gaisoku');
No7 = gaisoku_maxpoint_FFT;
load('Tsuji_gaisoku');
No8 = gaisoku_maxpoint_FFT;
load('Usui_gaisoku');
No9 = gaisoku_maxpoint_FFT;
load('Rikiya_gaisoku');
No10 = gaisoku_maxpoint_FFT;
load('Yamao_gaisoku');
No11 = gaisoku_maxpoint_FFT;
sokutei = [1 2 3];
figure;
plot(sokutei,No1,'-o');
xlabel('測定日');
ylabel('emgRMS');
title('外側広筋');
xticks([1 2 3])
xticklabels({'初回測定','中間測定','最終測定'})
hold on;
plot(sokutei,No2,'-o');
hold on;
plot(sokutei,No3,'-o');
hold on;
plot(sokutei,No4,'-o');
hold on;
plot(sokutei,No5,'-o');
hold on;
plot(sokutei,No6,'-o');
hold on;
plot(sokutei,No7,'-o');
hold on;
plot(sokutei,No8,'-o');
hold on;
plot(sokutei,No9,'-o');
hold on;
plot(sokutei,No10,'-o');
hold on;
plot(sokutei,No11,'-o');
legend({'Ikeda','Watanabe','Monobe','Suzuki','Takano','Okamura','Takechi','Tsuji','Usui','Fujii','Yamao'},'Location','northwest','NumColumns',2);
data = vertcat(No1,No2,No3,No4,No5,No6,No7,No8,No8,No9,No10,No11);
[h p] = ttest(data(:,1),data(:,3));

load('Ikeda_naisoku');
No1 = naisoku_maxpoint_FFT;
load('Nabe_naisoku');
No2 = naisoku_maxpoint_FFT;
load('Monobe_naisoku');
No3 = naisoku_maxpoint_FFT;
load('Suzuki_naisoku');
No4 = naisoku_maxpoint_FFT;
load('Kaito_naisoku');
No5 = naisoku_maxpoint_FFT;
load('Okamura_naisoku');
No6 = naisoku_maxpoint_FFT;
load('Takechi_naisoku');
No7 = naisoku_maxpoint_FFT;
load('Tsuji_naisoku');
No8 = naisoku_maxpoint_FFT;
load('Usui_naisoku');
No9 = naisoku_maxpoint_FFT;
load('Rikiya_naisoku');
No10 = naisoku_maxpoint_FFT;
load('Yamao_naisoku');
No11 = naisoku_maxpoint_FFT;
sokutei = [1 2 3];
figure;
plot(sokutei,No1,'-o');
xlabel('測定日');
ylabel('emgRMS');
title('内側広筋');
xticks([1 2 3])
xticklabels({'初回測定','中間測定','最終測定'})
hold on;
plot(sokutei,No2,'-o');
hold on;
plot(sokutei,No3,'-o');
hold on;
plot(sokutei,No4,'-o');
hold on;
plot(sokutei,No5,'-o');
hold on;
plot(sokutei,No6,'-o');
hold on;
plot(sokutei,No7,'-o');
hold on;
plot(sokutei,No8,'-o');
hold on;
plot(sokutei,No9,'-o');
hold on;
plot(sokutei,No10,'-o');
hold on;
plot(sokutei,No11,'-o');
legend({'Ikeda','Watanabe','Monobe','Suzuki','Takano','Okamura','Takechi','Tsuji','Usui','Fujii','Yamao'},'Location','northwest','NumColumns',2);
data = vertcat(No1,No2,No3,No4,No5,No6,No7,No8,No8,No9,No10,No11);
[h p] = ttest(data(:,1),data(:,3));
