load('Ikeda_gaisoku');
No1 = gaisoku_rms;
load('Nabe_gaisoku');
No2 = gaisoku_rms;
load('Monobe_gaisoku');
No3 = gaisoku_rms;
load('Suzuki_gaisoku');
No4 = gaisoku_rms;
load('Kaito_gaisoku');
No5 = gaisoku_rms;
load('Okamura_gaisoku');
No6 = gaisoku_rms;
load('Takechi_gaisoku');
No7 = gaisoku_rms;
load('Tsuji_gaisoku');
No8 = gaisoku_rms;
load('Usui_gaisoku');
No9 = gaisoku_rms;
load('Rikiya_gaisoku');
No10 = gaisoku_rms;
load('Yamao_gaisoku');
No11 = gaisoku_rms;
sokutei = [1 2 3];
figure;
plot(sokutei,No1,'-o');
xlabel('‘ª’è“ú');
ylabel('emgRMS(v)');
title('‹Ø“d}RMS‘JˆÚ-ŠO‘¤L‹Ø-');
xticks([1 2 3])
xticklabels({'‰‰ñ‘ª’è','’†ŠÔ‘ª’è','ÅI‘ª’è'})
hold on;
plot(sokutei,No2,'-o');
hold on;
plot(sokutei,No3,'-o');
hold on;
plot(sokutei,No4,'-o');
hold on;
plot(sokutei,No5,'-o');
hold on;
plot(sokutei,No6,'-o');
hold on;
plot(sokutei,No7,'-o');
hold on;
plot(sokutei,No8,'-o');
hold on;
plot(sokutei,No9,'-o');
hold on;
plot(sokutei,No10,'-o');
hold on;
plot(sokutei,No11,'-o');
%legend({'Ikeda','Watanabe','Monobe','Suzuki','Takano','Okamura','Takechi','Tsuji','Usui','Fujii','Yamao'},'Location','northwest','NumColumns',2);
%data = vertcat(No1,No2,No3,No4,No5,No6,No7,No8,No8,No9,No10,No11);
[h p] = ttest(data(:,1),data(:,3));

